line1=input("Enter text to write to the file: ")
file1=open("output.txt","w")
file1.write(line1)
print('Data successfully written to output.txt.')
file1.close()
line2=input("Enter additional text to append: ")
file2=open("output.txt","a")
file2.write('\n'+line2)
print('Data successfully appended.')
file2.close()
print("Final content of output.txt:")
file3=open("output.txt","r")
print(file3.read())
file3.close()